language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/dogs
deploy:
  provider: heroku
  app:
    master: best-in-dogs
  api_key:
    secure: KT2Tg0ua8P1DreyCpSqtSYGQiSNv0s7e3S+N2mC7uVwWbvnr4aO7MCF9U4+Z7K6jdNHD9DJ+BaxXlA2dAMuwkvKU4wa1Lw6wHRd6LUaPIH3+bgIjuZh1WP6z/CduA8510xP9fPHeFGoNJXR/0SumIlo5Di//Xi6ds8Rag7BLcI8bK0szI4SNQBfjM6pTt+RSLBoE0kpj5ntrTFTg8wjSy607xzFdsiLdHSKvU2Sw5x9YApQqjvU+57DP3LJyqlIFru3W4yNOEbM+AlDOP/+G0uGwKtSpABTNz0Fy5952Ul0mdBqCLT+YBAT6fdfnzLMdtEQqFRsezYVGnOia5u+Lg3bxoT+QAIebndFiC528gFQldr1eqM3cq3dPTOqf9TjDYFFJg+Q26DEa7/IsueTilaVW/ixfhr2S5uuz6d6hd7gf17MhQLwEb+vycaQkx5kWevQB2GOVDKslPA/Tg3i1DJqrKv8ohMd+n/Z5UAQFuNR58rpGnB2j55S3G8i9R4BdqAPrpR59nkQL6UPYfihwrcWYO01P6xPcfFPz7CEiNzHSCrHPHk+qX4ApmImgQPRoKdv3DIKjZO4ALKX9+oSgrHNn4eIbVqH+TeQcDQX8dlcU73/6u/h/s6O55dnTyAjSx/NhFl8chnu0xEA1Zot3YDyKiWUe2NcAD8VCFQfVG7U=

app: best-in-dogs